#!/usr/bin/env python
import argparse
parser = argparse.ArgumentParser(description = "Plot veto efficiency")
parser.add_argument('-d','--debug', default=False, dest = 'BUG')
parser.add_argument('-k','--kinematic', default='energy', dest = 'KIN')
parser.add_argument('-n','--numbermuons', default='1', type=int, dest = 'NUM')
args = parser.parse_args()

from icecube import icetray, dataclasses, dataio
from icecube import phys_services, simclasses, MuonGun
from I3Tray import I3Tray
from icecube.icetray import I3Units
from icecube.MuonGun import load_model, StaticSurfaceInjector, Cylinder, OffsetPowerLaw, BundleConfiguration, BundleEntry

import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import numpy as np


def take_ratios(numerator, denominator):
    ratio = list()
    for i in range(len(numerator)):
        if (denominator[i] == 0): n_ratio = 0
        else: n_ratio = numerator[i]/ denominator[i]
        ratio.append(n_ratio)
    return ratio

#load a long list of files
file_name = 'file_list.txt'
file_list = open(file_name).read().splitlines()
infile    = dataio.I3FrameSequence(file_list)
normalizataion  = len(file_list)
print "loaded your MC"

#initialize values
m_z_1 = []; m_z_2 = [];
m_e_1 = []; m_e_2 = [];
m_v0_1 = []; m_v0_2 = [];
m_v5_1 = []; m_v5_2 = [];
m_v10_1 = []; m_v10_2 = [];
m_w_1 = []; m_w_2 = [];
#initialize the loop 
event_count = 1
for frame in infile:
    if(event_count%50000 == 0):
        print "Event: "+ str(event_count)
        if(args.BUG): break
    if ("I3MCTree" in frame) and ("VHESelfVeto_10" in frame):
        event_count += 1
        number_muons = 0;
        muon_z_1 = 0.0; muon_z_2 = 0.0; #zenith
        muon_e_1 = 0.0; muon_e_2 = 0.0; #energy
        muon_w_1 = 0.0; muon_w_2 = 0.0; #weight
        muon_v0_1 = 0.0; muon_v0_2 = 0.0; #pass PE > 0 veto
        muon_v5_1 = 0.0; muon_v5_2 = 0.0; #pass PE > 5 veto
        muon_v10_1 = 0.0; muon_v10_2 = 0.0; #pass PE > 10 veto
        for particle in frame["I3MCTree"]:
            if particle.type == dataclasses.I3Particle.ParticleType.MuMinus:
                number_muons += 1 #count the muons
                energy = np.log10(particle.energy / I3Units.GeV) #sort by log10 energy
                if  (energy > muon_e_1):
                    muon_z_2 = muon_z_1; muon_z_1 = np.cos(particle.dir.zenith);
                    muon_e_2 = muon_e_1; muon_e_1 = energy;
                    muon_w_2 = muon_w_1; muon_w_1 = frame["MuonWeight"].value/normalizataion;
                    muon_v0_2 = muon_v0_1; muon_v0_1 = (1-int(frame["VHESelfVeto_0"].value)) * muon_w_1;
                    muon_v5_2 = muon_v5_1; muon_v5_1 = (1-int(frame["VHESelfVeto_5"].value)) * muon_w_1;
                    muon_v10_2 = muon_v10_1; muon_v10_1 = (1-int(frame["VHESelfVeto_10"].value)) * muon_w_1;
                elif(energy > muon_e_2):
                    muon_z_2 = np.cos(particle.dir.zenith);
                    muon_e_2 = energy;
                    muon_w_2 = frame["MuonWeight"].value/normalizataion;
                    muon_v0_2 = (1-int(frame["VHESelfVeto_0"].value)) * muon_w_2;
                    muon_v5_2 = (1-int(frame["VHESelfVeto_5"].value)) * muon_w_2;
                    muon_v10_2 = (1-int(frame["VHESelfVeto_10"].value)) * muon_w_2;
        if  (number_muons == 2 and (args.NUM == 2)):
            m_z_1.append(muon_z_1); m_z_2.append(muon_z_2);
            m_e_1.append(muon_e_1); m_e_2.append(muon_e_2);
            m_v0_1.append(muon_v0_1); m_v0_2.append(muon_v0_2);
            m_v5_1.append(muon_v5_1); m_v5_2.append(muon_v5_2);
            m_v10_1.append(muon_v10_1); m_v10_2.append(muon_v10_2);
            m_w_1.append(muon_w_1); m_w_2.append(muon_w_2);
        if  (number_muons == 1 and args.NUM == 1):
            m_z_1.append(muon_z_1);
            m_e_1.append(muon_e_1);
            m_v0_1.append(muon_v0_1);
            m_v5_1.append(muon_v5_1);
            m_v10_1.append(muon_v10_1);
            m_w_1.append(muon_w_1);
print "Processed " +str(event_count)+ " events generated by you!"

xbins= 50
xmin = 0; xmax = 0;
x_values = 0
if(args.KIN == 'energy'): 
    x_values = m_e_1
    xmin = 2; xmax = 6;
if(args.KIN == 'zenith'): 
    x_values = m_z_1
    xmin = 0; xmax = 1;
num0_vals = plt.hist(x_values, weights=m_v0_1, bins=xbins, range=(xmin,xmax), log=False, histtype='step', label='PE > 0')
num5_vals = plt.hist(x_values, weights=m_v5_1, bins=xbins, range=(xmin,xmax), histtype='step', label='PE > 5')
num10_vals = plt.hist(x_values, weights=m_v10_1, bins=xbins, range=(xmin,xmax), histtype='step', label='PE > 10')
den_vals = plt.hist(x_values, weights=m_w_1, bins=xbins, range=(xmin,xmax), histtype='step', label='all events')
acceptance0 = take_ratios(num0_vals[0],den_vals[0])
acceptance5 = take_ratios(num5_vals[0],den_vals[0])
acceptance10 = take_ratios(num10_vals[0],den_vals[0])
xvals   = den_vals[1][:-1]
#plt.clf()

#plt.plot(xvals, acceptance0, label='PE > 0')
#plt.plot(xvals, acceptance5, label='PE > 5')
#plt.plot(xvals, acceptance10, label='PE > 10')
plt.ylabel("Acceptance")
if(args.KIN == 'energy'): 
    plt.xlabel("log10 (E / GeV)")
    plt.legend(loc='upper right')
if(args.KIN == 'zenith'): 
    plt.xlabel("cos (theta)")
    plt.legend(loc='lower right')
#plt.show()
plt.savefig("debugging_"+args.KIN+"_dist_bundle_"+str(args.NUM)+".pdf")
print "Made file: debugging_" + args.KIN+"_dist_bundle_"+str(args.NUM)+".pdf"
